---
name: agda
on:
  push:
    branches: [master]
    paths: ['**.agda']
jobs:
  check:
    name: Check all.agda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wenkokke/setup-agda@latest
        with:
          agda-version: '2.6.2.2'
      - run: agda all.agda
