---
name: formalism
on:
  push:
    branches: [master]
jobs:
  formalism:
    name: Build formalism.pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: formalism.tex
      - uses: actions/upload-artifact@v3
        with:
          name: formalism
          path: formalism.pdf
